Lightbeam/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('adminapp.urls')),
    url(r'^', include('userapp.urls')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from userapp.alloc import init_periodic_check
# init_periodic_check()

userapp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/', views.register, name='register'),
    url(r'^home/', views.home, name='home'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^add-book/', views.add_book, name='add_book'),
    url(r'^add-new-book/', views.add_new_book, name='add_new_book'),
    url(r'^get-book-suggestion/', views.get_book_suggestion, name='get_book_suggestion'),
    url(r'^add-product/', views.add_product, name='add_product'),
    url(r'^user-books/', views.user_books, name='user_books'),
    url(r'^search/', views.search, name='search'),
    url(r'^notifications/', views.notifications, name='notifications'),
    url(r'^search-books/', views.search_books, name='search_books'),
    url(r'^user-requests/', views.user_requests, name='user_requests'),
    url(r'^book-request/', views.book_request, name="book_request"),
    url(r'^save-profile/', views.save_profile, name="save-profile"),
    url(r'^view-book/(?P<product_id>[0-9]+)$', views.view_book, name='view_book'),
    url(r'^user/(?P<user_id>[0-9]+)$', views.profile, name='profile'),
    url(r'^confirm-product/', views.confirm_product, name='confirm_product'),
    url(r'^delete-product/', views.delete_product, name='delete_product'),
    url(r'^delete-request/', views.delete_request, name='delete_request'),
]

userapp/models.py
from django.db import models
from datetime import datetime, timedelta

from .verify import *

# Create your models here.

class User(models.Model):
    # id : integer
    ROLES = (
        ('U', 'User'),
        ('A', 'Admin'),
        ('M', 'Moderator')
    )

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=50)
    student_id = models.CharField(max_length=7, unique=True)       # 1305011 style
    password = models.CharField(max_length=30)
    mobile_no = models.CharField(max_length=11, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    profile_picture = models.ImageField(upload_to='profile_picture/', default='profile_picture/default-user.png')
    role = models.CharField(max_length=1, default='U', choices=ROLES)

    def __str__(self):
        return self.student_id

    def save(self, *args, **kwargs):
        if (verifyUser(self)):
            super(User, self).save(*args, **kwargs)
        else:
            raise Exception
            'user information is invalid'



class Author(models.Model):
    # id : integer
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Book(models.Model):
    # id : integer
    APROVAL_STATUSES = (
        ('P', 'Pending'),
        ('A', 'Approved'),
    )
    name = models.CharField(max_length=50)
    authors = models.ManyToManyField(Author)
    categories = models.ManyToManyField(Category, blank=True)
    cover_picture = models.ImageField(upload_to='book_picture/', default='book_picture/default-book.png')
    approval_status = models.CharField(max_length=1, default='A', choices=APROVAL_STATUSES)

    @property
    def author_list(self):
        list = ""
        for author in self.authors.all():
            list = list + author.name + ', '
        return list[:-2]

    def __str__(self):
        return self.name


class Product(models.Model):
    # id : integer
    PRINT_STATUSES = (
        ('A', 'American'),
        ('I', 'Indian'),
        ('P', 'Photocopy'),
    )
    CONDITIONS = (
        ('G', 'Good'),
        ('M', 'Medium'),
        ('B', 'Bad'),
    )
    CONFIRMATIONS = (
        ('N', 'No Confirmation'),
        ('O', 'Owner Confirmed'),
        ('R', 'Receiver Confirmed'),
        ('B', 'Both Side Confirmation'),
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    print_status = models.CharField(max_length=1, null=True, blank=True, choices=PRINT_STATUSES)
    condition = models.CharField(max_length=1, null=True, blank=True, choices=CONDITIONS)
    edition = models.IntegerField(null=True, blank=True)
    price = models.IntegerField(default=0)
    date_time = models.DateTimeField(default=datetime.now, blank=True)
    confirmation = models.CharField(max_length=1, null=True, blank=True, choices=CONFIRMATIONS)

    @property
    def serial_count(self):
        return Serial.objects.filter(product=self).count()

    class Meta:
        unique_together = (("owner", "book"),)

    def __str__(self):
        return self.book.name + ' from ' + self.owner.student_id

    def save(self, *args, **kwargs):
        if (verifyProduct(self)):
            super(Product, self).save(*args, **kwargs)
        else:
            raise Exception
            'product information is invalid'

    @property
    def isBooked(self):
        return Product.objects.filter(currentholder__product_id=self.id).count() == 1

    def condition_verbose(self):
        return dict(Product.CONDITIONS)[self.condition]

    def print_status_verbose(self):
        return dict(Product.PRINT_STATUSES)[self.print_status]


class Serial(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    serial_no = models.IntegerField()

    class Meta:
        unique_together = (("product", "user"),)

    def __str__(self):
        return self.product.book.name + ' - ' + self.user.student_id + ' - ' + str(self.serial_no)

    def save(self, *args, **kwargs):
        if (self.serial_no > 0):
            super(Serial, self).save(*args, **kwargs)
        else:
            raise Exception
            'serial information is invalid'


class CurrentHolder(models.Model):
    # serial = models.ForeignKey(Serial, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, unique=True)
    holder = models.ForeignKey(User, on_delete=models.CASCADE)
    date_time = models.DateTimeField(default=datetime.now, blank=True)

    @property
    def last_time(self):
        return self.date_time + timedelta(days=3)

    def __str__(self):
        return self.product.book.name + ' - ' + self.holder.student_id


class Notification(models.Model):
    NOTIFICATIONS = (
        ('CH', 'Current Holding'),
        ('TH', 'Timeout Holding'),
        ('BB', 'Book Booked'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    text = models.CharField(max_length=100)
    link = models.CharField(max_length=100, null=True, blank=True)
    type = models.CharField(max_length=2, choices=NOTIFICATIONS)
    date_time = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.user.student_id + ' - ' + self.type

templates/add-book.html
<!DOCTYPE html>
<html lang="en">

<head>

    {% load staticfiles %}

    <meta charset="utf-8">
    <meta name="robots" content="all,follow">
    <meta name="googlebot" content="index,follow,snippet,archive">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Lightbeam - Online Course Book Solution</title>

    <meta name="keywords" content="">

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,500,700,800' rel='stylesheet' type='text/css'>

    <!-- Bootstrap and Font Awesome css -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- Css animations  -->
    <link href="../static/css/animate.css" rel="stylesheet">

    <!-- Theme stylesheet, if possible do not edit this stylesheet -->
    <link href="../static/css/style.default.css" rel="stylesheet" id="theme-stylesheet">

    <!-- Custom stylesheet - for your changes -->
    <link href="../static/css/custom.css" rel="stylesheet">

    <!-- Responsivity for older IE -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

    <!-- Favicon and apple touch icons-->
    <link rel="shortcut icon" href="../static/img/favicon.ico" type="image/x-icon" />
</head>

<body>


    <div id="all">

        <div id="heading-breadcrumbs">
            <div class="container">
                <div class="row">
                    <h1>Add books</h1>
                </div>
            </div>
        </div>

        <div id="content" class="clearfix">

            <div class="container">

                <div class="row">

                    <!-- *** LEFT COLUMN ***
			 _________________________________________________________ -->

                    <div class="col-md-6 clearfix" id="add-book">

                        <div class="box clearfix">
                            <div class="heading">
                                <h3 class="text-uppercase">Book details</h3>
                            </div>
                            <div id="add-new-book-banner" style="float: right">
                                If you can't find the book, <a href="#" onclick="Add_New_Book();">you can add that.</a>
                            </div>
                            <div id="add-new-book"></div>
                            {% if addBookForm.errors %}
                            <div class="alert alert-danger">
                                <strong>Error!</strong> Enter valid book name from suggestions.
                            </div>
                            {% elif addBookForm.success == 1 %}
                            <div class="alert alert-success">
                                <strong>Success!</strong> You have added the book.
                            </div>
                            {% elif addBookForm.success == 2 %}
                            <div class="alert alert-warning">
                                <strong>Warning!</strong> You have already added this book. Your entry is ignored.
                            </div>
                            {% endif %}

                            <form id="add-book-form" action="/add-product/" method="post">
                                {% csrf_token %}
                                {% for field in addBookForm %}
                                    <div class="form-group">
                                        <label style="font-size: large"> {{ field.label }} </label></br>
                                        {{ field }}
                                    </div>
                                {% endfor %}

                                <div class="col-sm-12 text-center">
                                    <button type="submit" class="btn btn-template-main"><i class="fa fa-save"></i> Add Book</button>
                                </div>

                            </form>

                        </div>

                    </div>

                    <div class="col-md-3 clearfix" id="add-books">

                    </div>
                    <!-- /.col-md-9 -->

                    <!-- *** LEFT COLUMN END *** -->

                    <!-- *** RIGHT COLUMN ***
			 _________________________________________________________ -->

                    <div class="col-md-3">
                        <!-- *** CUSTOMER MENU ***
 _________________________________________________________ -->
                        <div class="panel panel-default sidebar-menu">

                            <div class="panel-heading">
                                <h3 class="panel-title">User section</h3>
                            </div>

                            <div class="panel-body">

                                <ul class="nav nav-pills nav-stacked">
                                    <li>
                                        <a href="/notifications/"><i class="fa fa-newspaper-o"></i> Notifications</a>
                                    </li>
									<li class="active">
                                        <a href="/add-book/"><i class="fa fa-book"></i> Add books</a>
                                    </li>
									<li>
                                        <a href="/search-books/"><i class="fa fa-search"></i> Search books</a>
                                    </li>
                                    <li>
                                        <a href="/user-books/"><i class="fa fa-list"></i> My books</a>
                                    </li>
                                    <li>
                                        <a href="/user-requests/"><i class="fa fa-heart"></i> My requests</a>
                                    </li>
                                    <li>
                                        <a href="/home/"><i class="fa fa-user"></i> My account</a>
                                    </li>
                                    <li>
                                        <a href="/logout/"><i class="fa fa-sign-out"></i> Logout</a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                        <!-- /.col-md-3 -->

                        <!-- *** CUSTOMER MENU END *** -->
                    </div>

                    <!-- *** RIGHT COLUMN END *** -->

                </div>
                <!-- /.row -->

            </div>
            <!-- /.container -->
        </div>
        <!-- /#content -->


        <!-- *** FOOTER ***
_________________________________________________________ -->

        <footer id="footer">
            <div class="container">
                <div class="col-md-6 col-sm-6">
                    <h4>About us</h4>

                    <p>This is a term project by Tanjim (1305013) and Tareq(1305011) for Software Development course at CSE, BUET.</p>

                </div>

                <div class="col-md-6 col-sm-6">

                    <h4>Contact</h4>

                    <a href="#" class="facebook" data-animate-hover="pulse"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="email" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
                    <a href="#" class="external gplus" data-animate-hover="pulse"><i class="fa fa-google-plus"></i></a>
                    <a href="#" class="external twitter" data-animate-hover="pulse"><i class="fa fa-twitter"></i></a>

                </div>
            </div>
            <!-- /.container -->
        </footer>
        <!-- /#footer -->

        <!-- *** FOOTER END *** -->

        <!-- *** COPYRIGHT ***
_________________________________________________________ -->

        <div id="copyright">
            <div class="container">
                <div class="col-md-12">
                    <p class="pull-left">&copy; 2017. Lightbeam</p>
{#                    <p class="pull-right">Template by <a href="https://bootstrapious.com">Bootstrapious</a> & <a href="https://remoteplease.com">Remote Please</a>#}
                         <!-- Not removing these links is part of the license conditions of the template. Thanks for understanding :) If you want to use the template without the attribution links, you can do so after supporting further themes development at https://bootstrapious.com/donate  -->
                    </p>
                </div>
            </div>
        </div>
        <!-- /#copyright -->

        <!-- *** COPYRIGHT END *** -->



    </div>
    <!-- /#all -->


    <!-- #### JAVASCRIPT FILES ### -->

    <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript">
    </script> <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>



    <!-- JAVASCRIPT + JQuery functions  -->


    <script src="../static/js/lightbeam.autocomplete.js" type="text/javascript"></script>

    <script src="../static/js/lightbeam.addnewbook.js?2" type="text/javascript"></script>


</body>

</html>

templates/user-books.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="robots" content="all,follow">
    <meta name="googlebot" content="index,follow,snippet,archive">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Lightbeam - Online Course Book Solution</title>

    <meta name="keywords" content="">

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,500,700,800' rel='stylesheet' type='text/css'>

    <!-- Bootstrap and Font Awesome css -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- Css animations  -->
    <link href="../static/css/animate.css" rel="stylesheet">

    <!-- Theme stylesheet, if possible do not edit this stylesheet -->
    <link href="../static/css/style.default.css" rel="stylesheet" id="theme-stylesheet">

    <!-- Custom stylesheet - for your changes -->
    <link href="../static/css/custom.css" rel="stylesheet">

    <!-- Responsivity for older IE -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

    <!-- Favicon and apple touch icons-->
    <link rel="shortcut icon" href="../static/img/favicon.ico" type="image/x-icon" />
</head>

<body>


    <div id="all">

        <div id="heading-breadcrumbs">
            <div class="container">
                <div class="row">
                    <h1>My Books</h1>
                </div>
            </div>
        </div>

        <div id="content">
            <div class="container">

                <div class="row">

                    <!-- *** LEFT COLUMN ***
			 _________________________________________________________ -->

                    <div class="col-md-9 clearfix" id="user-books">
                        <p class="text-muted lead">You currently have {{ userProducts.count }} book(s).</p>
                        <div class="box">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Book</th>
                                            <th>Authors</th>
                                            <th>Status</th>
                                            <th>Price</th>
                                            <th>Edition</th>
                                            <th>Print</th>
                                            <th>Condition</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for product in userProducts %}
                                         <tr id="tr-{{ product.id }}">
{#                                                <td>#}
{#                                                    <a href="#">#}
{#                                                        <img src="{{ product.owner.profile_picture.url }}" style="max-width: 30%;height: auto;" alt={{ product.book.name }} >#}
{#                                                    </a>#}
{#                                                </td>#}
                                            <td><a href="/view-book/{{ product.id }}">{{ product.book.name }}</a></td>
                                            <td>{% for author in product.book.authors.all %}
                                                {{ author.name }} </br>
                                            {% endfor %}
                                            </td>
                                            <td>
                                                {% if product.confirmation == 'O' %}
                                                     <label id="status-{{ product.id }}" class="label label-primary">Confimed by Owner</label>
                                                {% elif product.confirmation == 'R' %}
                                                     <label id="status-{{ product.id }}" class="label label-primary">Confimed by Receiver</label>
                                                {% elif product.confirmation == 'B' %}
                                                     <label id="status-{{ product.id }}" class="label label-success">Confimed by Both</label>
                                                {% elif product.book.approval_status == 'P' %}
                                                    <label id="status-{{ product.id }}" class="label label-warning">Pending Approval</label>
                                                {% elif product.isBooked %}
                                                    <label id="status-{{ product.id }}" class="label label-info">Booked</label>
                                                {% elif product.book.approval_status == 'A' %}
                                                    <label id="status-{{ product.id }}" class="label label-default">Not Booked</label>
                                                {% endif %}
                                            </td>
                                            <td>{{ product.price }}</td>

                                            {% if product.edition != 0 %}<td>{{ product.edition }}</td>
                                            {% else %}<td> {{ none }} </td>
                                            {% endif %}
                                            {% if product.print_status %}<td>{{ product.get_print_status_display }}</td>
                                            {% else %}<td> {{ none }} </td>
                                            {% endif %}
                                            {% if product.condition %}<td>{{ product.get_condition_display }}</td>
                                            {% else %}<td> {{ none }} </td>
                                            {% endif %}

                                            <td>
                                                {% if product.confirmation == 'O' or product.confirmation == 'B' %}
                                                    <button id="action-{{ product.id }}" class="btn btn-success btn-xs disabled">Confirmed</button>
                                                {% elif product.isBooked %}
                                                    <button id="action-{{ product.id }}" class="btn btn-primary btn-xs" onclick="confirmProduct({{ product.id }}, 'O')">Confirm</button>
                                                {% else %}
                                                    <button id="action-{{ product.id }}" class="btn btn-danger btn-xs" onclick="deleteProduct({{ product.id }})">Delete</button>
                                                {% endif %}
                                            </td>
                                         </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>

{#                            <img src="{{ product.book.cover_picture.url }}" >#}


                        </div>

                    </div>
                    <!-- /.col-md-9 -->

                    <!-- *** LEFT COLUMN END *** -->

                    <!-- *** RIGHT COLUMN ***
			 _________________________________________________________ -->

                    <div class="col-md-3">
                        <!-- *** CUSTOMER MENU ***
 _________________________________________________________ -->
                        <div class="panel panel-default sidebar-menu">

                            <div class="panel-heading">
                                <h3 class="panel-title">User section</h3>
                            </div>

                            <div class="panel-body">

                                <ul class="nav nav-pills nav-stacked">
                                    <li>
                                        <a href="/notifications/"><i class="fa fa-newspaper-o"></i> Notifications</a>
                                    </li>
									<li>
                                        <a href="/add-book/"><i class="fa fa-book"></i> Add books</a>
                                    </li>
									<li>
                                        <a href="/search-books/"><i class="fa fa-search"></i> Search books</a>
                                    </li>
                                    <li class="active">
                                        <a href="/user-books/"><i class="fa fa-list"></i> My books</a>
                                    </li>
                                    <li>
                                        <a href="/user-requests/"><i class="fa fa-heart"></i> My requests</a>
                                    </li>
                                    <li>
                                        <a href="/home/"><i class="fa fa-user"></i> My account</a>
                                    </li>
                                    <li>
                                        <a href="/logout/"><i class="fa fa-sign-out"></i> Logout</a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                        <!-- /.col-md-3 -->

                        <!-- *** CUSTOMER MENU END *** -->
                    </div>

                    <!-- *** RIGHT COLUMN END *** -->

                </div>
                <!-- /.row -->

            </div>
            <!-- /.container -->
        </div>
        <!-- /#content -->


        <!-- *** FOOTER ***
_________________________________________________________ -->

        <footer id="footer">
            <div class="container">
                <div class="col-md-6 col-sm-6">
                    <h4>About us</h4>

                    <p>This is a term project by Tanjim (1305013) and Tareq(1305011) for Software Development course at CSE, BUET.</p>

                </div>

                <div class="col-md-6 col-sm-6">

                    <h4>Contact</h4>

                    <a href="#" class="facebook" data-animate-hover="pulse"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="email" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
                    <a href="#" class="external gplus" data-animate-hover="pulse"><i class="fa fa-google-plus"></i></a>
                    <a href="#" class="external twitter" data-animate-hover="pulse"><i class="fa fa-twitter"></i></a>

                </div>
            </div>
            <!-- /.container -->
        </footer>
        <!-- /#footer -->

        <!-- *** FOOTER END *** -->

        <!-- *** COPYRIGHT ***
_________________________________________________________ -->

        <div id="copyright">
            <div class="container">
                <div class="col-md-12">
                    <p class="pull-left">&copy; 2017. Lightbeam</p>
{#                    <p class="pull-right">Template by <a href="https://bootstrapious.com">Bootstrapious</a> & <a href="https://remoteplease.com">Remote Please</a>#}
                         <!-- Not removing these links is part of the license conditions of the template. Thanks for understanding :) If you want to use the template without the attribution links, you can do so after supporting further themes development at https://bootstrapious.com/donate  -->
                    </p>
                </div>
            </div>
        </div>
        <!-- /#copyright -->

        <!-- *** COPYRIGHT END *** -->



    </div>
    <!-- /#all -->

    <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript">
    </script> <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>


    <script>
        var csrftoken = '{{ csrf_token }}';
    </script>
    <script src="../static/js/lightbeam.confirmproduct.js" type="text/javascript"></script>
    <script src="../static/js/lightbeam.deleteproduct.js" type="text/javascript"></script>

</body>

</html>